### ISSUE TITLE
error: fail to fetch 발생

### ISSUE THREAD

**Issue by yhs06285** [parkchamchi/GlossySnake#32]
현재 말씀해주신대로 장고 백엔드를 연결해서 결과값 출력을 하고자 하는데, fail to fetch 오류가 계속 발생해 이슈 올려드립니다. 며칠동안 코드를 바꿔도 계속 발생해서...혹시 해결법이 무엇인지 알고자 말씀드립니다.
![image](https://github.com/parkchamchi/GlossySnake/assets/164466719/64a03341-563a-40ca-a5dd-516b614c6ea3)

현재 백엔드는 이것을 사옹하고 있었습니다.
![image](https://github.com/parkchamchi/GlossySnake/assets/164466719/82648b62-7e16-4592-8b8c-45a0d949e3b4)

**Comment by parkchamchi** [comment]
확인해볼게요

**Comment by parkchamchi** [comment]
그 코드가 어느 브랜치에 있는건가요

**Comment by KangByungky** [comment]
아르바이트 중이라 답변이 늦었씁니다. 아직 push하지 않은 코드인데, src/frontend/mockup.html에서 
fetch함수에서 full url 부분을 "endpoint"+"api/v2/upload" 이렇게 바꾼 것입니다.

**Comment by parkchamchi** [comment]
제가 수정했을때는 작동하네요.
코드를 push하시지 않으면 제가 어떤 오류가 발생하는지 알수가 없네요. 코드 push 아끼지 마시고 아무 브랜치에 해주세요. master만 아니면 상관없어요.
아 그리고 이건 별개의 문젠데 (`net::ERR_CONNECTION_REFUSED`는 보통 프론트엔드 코드 문제) `/upload` 엔드포인트는 원래 있던 api v1 `/annotate` 엔드포인트의 body 내용이 달라요. 이건 design doc 참고하시면 될 것 같고요.

**Comment by yhs06285** [comment]
넵 알겠습니다 답변 주셔서 감사합니다. 퇴근 후에 코드 push하겠습니다
