### ISSUE TITLE
리다이렉션 발생 관련

### ISSUE THREAD

**Issue by yhs06285** [parkchamchi/GlossySnake#38]
현재 frontend 폴더의 mockup_network_success.html 파일을 사용 중인데, request 버튼을 누르면 로그에 제가 보낸 문자열을 볼 수 있는데, 페이지는 다시 초기 화면으로 돌아가는 상황이 발생합니다. 혹시 이에 대한 해결방법이 무엇인지 여쭙고자 이슈탭을 열었습니다.

https://github.com/parkchamchi/GlossySnake/assets/164466719/aebe672e-4b44-495d-9405-0accc96ca251

**Comment by parkchamchi** [comment]
브랜치 `frontend_ttestt` 맞죠? 제 경우에는 리다이렉트 현상이 나타나지 않는데 혹시 프론트엔드는 무슨 환경에서 돌리시나요? (파이선 스크립트 또는 "라이브 서버")

**Comment by yhs06285** [comment]
![image](https://github.com/parkchamchi/GlossySnake/assets/164466719/25f0775c-0558-4f32-bda5-ab9b506673a5)
아 라이브서버에서 실행했습니다. 다시 dbreset하고 실행해보니 리다이렉트되지 않고 결과값 나오는 것 같습니다. 감사합니다!
