### ISSUE TITLE
회원가입 시 500error 발생관련 이슈

### ISSUE THREAD

**Issue by yhs06285** [parkchamchi/GlossySnake#63]
![image](https://github.com/user-attachments/assets/1bddfdb2-0442-4c2f-829d-8d7e7ce29db9)
![image](https://github.com/user-attachments/assets/19ea8828-0794-4984-9aac-ec89944e3070)
안녕하세요 문장을 업로드하기 이전에 회원가입 기능이 먼저 필요할 것 같아 signup기능을 만들어서 http://127.0.0.1:56123/api/v4/rest-auth/registration/로 개인정보를 보내게끔 했는데 500error가 지속적으로 발생하여 이슈를 열었습니다. 혹시 해답을 알려주실 수 있을지 확인차 연락드립니다.

**Comment by parkchamchi** [comment]
`500`은 서버 문제라 백엔드 출력을 봐야합니다.
돌려보니까 아마 static 문제같은데 localhost랑 통신할때는
1. `src/backend/GlossySnakeBE/settings.py`의 `DEBUG`를 `True`로 하시던지
2. `src/backend`에서 `python manage.py collectstatic`을 돌리시던지
3. 아니면 이제 백엔드가 deploy되었으니 localhost말고 그냥 `glossysnake.com`이랑 통신하시면 됩니다. (이걸로)
