### ISSUE TITLE
mockup.html에 백엔드를 연결하고 결과를 응답할 때 403 forbidden error가 나타납니다.

### ISSUE THREAD

**Issue by codingwoong** [parkchamchi/GlossySnake#64]
![forbidden_403_error](https://github.com/user-attachments/assets/c33664b1-b07d-4597-91b1-812cfc4cd7fa)

에러의 원인을 짐작하기로는 로그인 기능과 관련해 권한이 부여되지 않아 발생하는 것 같으나 
1. email, password 등 정보를 /api/v4/rest-auth/login/로 전송하고 key 전송 받기
2. 임시 admin 권한 부여
3. index.html의 onFrontendUserGetTempUserButtonClicked() 함수 참조 등 
 
여러 방면으로 해결책을 모색하였으나 도저히 답이 나오지 않아 issue를 올립니다.

**Comment by parkchamchi** [comment]
fetch할 때
```js
credentials: "include",
```
넣어주세요

근데 `mockup.html`하고 `modified_mockup_with_csrf.html`은 왜 분리되어있나요?

**Comment by codingwoong** [comment]
작업의 편리성을 위해 분리되어 있습니다. 서버 응답을 위해 더 나은 결과물을 추출하려 일단 2개로 분리하였습니다. 빠른 시일 내에 병합/첨삭 과정을 진행하겠습니다

**Comment by codingwoong** [comment]
![include_but_403](https://github.com/user-attachments/assets/a96afb8a-7259-4f09-8e44-5e65d9d4e6a6)
fetch에 credentials: "include", 를 삽입하였으나 여전히 forbidden 403 error가 나타납니다

**Comment by parkchamchi** [comment]
코드가 브랜치에 올라가 있나요?
아까 코드를 보니까 upload하는 fetch함수가 여러개 있던데...

- 아 그리고 서버랑 통신은 cors때문에 안되서 개발할 때에는 로컬에서 돌려야 할 거에요

**Comment by codingwoong** [comment]
코드는 오늘 새벽에 커밋한 상태가 마지막입니다. mockup.html에 사용되는 fetch함수는 하나인 걸로 알고 있습니다. 어떤 부분을 말하시는 지 잘 모르겠습니다..

**Comment by parkchamchi** [comment]
그럼 브랜치에 올라간 코드는 credentials: "include"가 없는 코드란 말이죠?

**Comment by codingwoong** [comment]
네 맞습니다

**Comment by parkchamchi** [comment]
outdated
